zen-mod/ZEN

addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf, addons/remote_control/CfgEventHandlers.hpp, addons/remote_control/XEH_PREP.hpp, addons/remote_control/XEH_postInit.sqf, addons/remote_control/functions/fnc_handleMouseDblClick.sqf
=> Ability to ctrl + double click to remote control

addons/context_menu/functions/fnc_compileActions.sqf
=> Support missionConfigFile context menu actions

addons/attributes/RscAttributes.hpp, addons/attributes/XEH_PREP.hpp, addons/attributes/functions/fnc_attributeExec.sqf, addons/attributes/script_component.hpp, addons/attributes/stringtable.xml
=> Add exec attribute

addons/ai/functions/fnc_waypointLand.sqf, addons/attributes/functions/fnc_attributeWaypointType.sqf
- Improve reliability of BI's land waypoint by creating an invisible helipad at the waypoint's position
=> Improve reliability of land waypoint

addons/common/XEH_postInit.sqf, addons/modules/functions/fnc_moduleVisibility.sqf
=> Fix AI shooting invisible units

README.md
- Fix the readme after the organization change
- Increment version to 1.1.0
=> Fixed README.md after org change

addons/modules/functions/fnc_moduleCreateIED.sqf
=> Fix IED objects surviving explosion

addons/editor/XEH_preInit.sqf, addons/editor/functions/fnc_initDisplayCurator.sqf
- Set camera ceiling to 100'000 m.
- Set camera pitch limit to 89°.
=> Extend camera limits

AUTHORS.txt, addons/ai/stringtable.xml, addons/attributes/stringtable.xml, addons/common/stringtable.xml, addons/context_actions/stringtable.xml, addons/context_menu/stringtable.xml, addons/custom_modules/stringtable.xml, addons/doors/stringtable.xml, addons/editor/stringtable.xml, addons/garage/stringtable.xml, addons/main/stringtable.xml, addons/modules/stringtable.xml, addons/vision/stringtable.xml
Translating to German on the side, not yet done, but to show there is progress going on.
- Adds German translations for ZEN
0 missing stringtable entry/entries.
=> German translations

addons/ai/stringtable.xml, addons/attributes/stringtable.xml, addons/common/stringtable.xml, addons/context_actions/stringtable.xml, addons/context_menu/stringtable.xml, addons/custom_modules/stringtable.xml, addons/doors/stringtable.xml, addons/editor/stringtable.xml, addons/garage/stringtable.xml, addons/main/stringtable.xml, addons/modules/stringtable.xml, addons/vision/stringtable.xml
_*As of 2019.07.01_
- Add full Polish translation
=> Full Polish Translation

addons/camera/$PBOPREFIX$, addons/camera/CfgEventHandlers.hpp, addons/camera/XEH_PREP.hpp, addons/camera/XEH_postInit.sqf, addons/camera/XEH_preInit.sqf, addons/camera/XEH_preStart.sqf, addons/camera/config.cpp, addons/camera/functions/fnc_updateSettings.sqf, addons/camera/functions/script_component.hpp, addons/camera/initSettings.sqf, addons/camera/script_component.hpp, addons/camera/stringtable.xml, addons/editor/XEH_preInit.sqf, addons/editor/functions/fnc_initDisplayCurator.sqf
- Add settings to control curator camera properties: follow terrain, surface speed, and movement speeds
- Move fixes from #37 to new `camera` component
=> Add settings to control camera properties

addons/modules/functions/fnc_gui_fireMission.sqf, addons/modules/functions/fnc_moduleAmbientAnim.sqf, addons/modules/functions/fnc_moduleArsenal.sqf, addons/modules/functions/fnc_moduleAssignZeus.sqf, addons/modules/functions/fnc_moduleAttachFlag.sqf, addons/modules/functions/fnc_moduleAttachTo.sqf, addons/modules/functions/fnc_moduleBindVariable.sqf, addons/modules/functions/fnc_moduleChangeHeight.sqf, addons/modules/functions/fnc_moduleConvoyParameters.sqf, addons/modules/functions/fnc_moduleCreateIED.sqf, addons/modules/functions/fnc_moduleEquipWithECM.sqf, addons/modules/functions/fnc_moduleFlyHeight.sqf, addons/modules/functions/fnc_moduleGarrison.sqf, addons/modules/functions/fnc_moduleGroupSide.sqf, addons/modules/functions/fnc_moduleHeal.sqf, addons/modules/functions/fnc_moduleMakeInvincible.sqf, addons/modules/functions/fnc_modulePatrolArea.sqf, addons/modules/functions/fnc_moduleSimulation.sqf, addons/modules/functions/fnc_moduleSitOnChair.sqf, addons/modules/functions/fnc_moduleSuicideBomber.sqf, addons/modules/functions/fnc_moduleTurretOptics.sqf, addons/modules/functions/fnc_moduleUnGarrison.sqf, addons/modules/functions/fnc_moduleVisibility.sqf, addons/modules/stringtable.xml
- Improve error messages when modules are not placed on a unit/object
- Might need to take a look at other messages as well
- Close #22
=> Improve object attachment hints

README.md, addons/main/stringtable.xml, mod.cpp
Only one of these - the github.io site - actually broke anything but I thought I might as well change them all while I was there.
=> Change all links to new repository

addons/common/stringtable.xml, addons/context_menu/stringtable.xml, addons/editor/stringtable.xml
- Add periods at the end of setting descriptions
- Minor change but I think it looks better this way
=> Add periods to setting descriptions

addons/ai/XEH_preInit.sqf, addons/ai/functions/fnc_unGarrison.sqf, addons/common/XEH_postInit.sqf
=> Rotation of garrisoned units

addons/editor/functions/fnc_bi_curatorWaypointPlaced.sqf
- Fix https://feedback.bistudio.com/T85817
=> Fix cycle waypoint position

README.md
=> Fix README image on mobile

addons/modules/functions/fnc_gui_setDate.sqf
- Extend range to 1900-2050, same as 3DEN with new CBA update
=> Extend set date module year range

addons/modules/functions/fnc_gui_fireMission.sqf
=> Change fire mission default mode to target module

addons/attributes/RscAttributes.hpp, addons/attributes/XEH_PREP.hpp, addons/attributes/functions/fnc_buttonSide.sqf, addons/attributes/stringtable.xml, addons/common/XEH_PREP.hpp, addons/common/functions/fnc_changeGroupSide.sqf, addons/modules/functions/fnc_moduleGroupSide.sqf
- Add button to change side of group in group attributes display
- Add common `changeGroupSide` function
- Change group side module to use new common function
=> Add group side button to attributes display

addons/dialog/functions/fnc_create.sqf, addons/dialog/functions/fnc_gui_slider.sqf, addons/modules/CfgVehicles.hpp, addons/modules/XEH_PREP.hpp, addons/modules/XEH_postInit.sqf, addons/modules/config.cpp, addons/modules/functions/fnc_moduleWeather.sqf, addons/modules/script_component.hpp, addons/modules/stringtable.xml, docs/dynamic_dialog.md
- Add change weather module, Close #30 
- Change dialog `SLIDER` control's decimal argument to formatting
- Allows custom formatting code (example: degree symbol)
=> Add change weather module

addons/dialog/functions/fnc_create.sqf, addons/dialog/functions/fnc_gui_toolbox.sqf, addons/dialog/gui.hpp, addons/modules/functions/fnc_moduleCreateIED.sqf, addons/modules/functions/fnc_moduleCreateMinefield.sqf, addons/modules/functions/fnc_moduleEarthquake.sqf, addons/modules/functions/fnc_moduleGarrison.sqf, addons/modules/functions/fnc_modulePatrolArea.sqf, addons/modules/functions/fnc_moduleSuicideBomber.sqf, addons/modules/functions/fnc_moduleTurretOptics.sqf, docs/dynamic_dialog.md
- Improve dialog toolbox control with support any number of rows and columns
- Add a wide variant - `TOOLBOX:WIDE`
=> Improve dialog toolbox control

addons/attributes/CfgWaypointTypes.hpp, addons/attributes/RscAttributes.hpp, addons/attributes/XEH_PREP.hpp, addons/attributes/XEH_preStart.sqf, addons/attributes/config.cpp, addons/attributes/functions/fnc_attributeWaypointType.sqf, addons/attributes/functions/fnc_compileWaypoints.sqf
- Add config to easily configure waypoint types available to Zeus
- Attribute UI will scale automatically as more are added
=> Add waypoint types config

addons/modules/RscAttributes.hpp, addons/modules/functions/fnc_gui_sideRelations.sqf
- Improve side combos by preserving currently selected side in combo 2 when combo 1 selection changes (if possible)
- Remove transparent background from combos
=> Improve side relations GUI combo selection

addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf, addons/context_actions/functions/fnc_rearmVehicles.sqf, addons/context_actions/functions/fnc_refuelVehicles.sqf, addons/context_actions/functions/fnc_repairVehicles.sqf, addons/modules/functions/fnc_moduleWeather.sqf
- Remove tabs from `fnc_bi_showCuratorAttributes`
- Move remaining includes to top
=> Minor cleanup of tabs and includes

addons/modules/functions/fnc_moduleFireMission.sqf
- title, Close #98 
- I think one decimal place is better than integer
=> Round artillery ETA message

addons/modules/functions/fnc_moduleGarrison.sqf
=> Change garrison minimum range to 5

addons/modules/functions/fnc_moduleCreateTarget.sqf
=> Fix independent side laser target error

addons/editor/functions/fnc_declutterEmptyTree.sqf
- title, should be a bit faster after first display load
=> Cache declutter empty tree faction names

addons/editor/RscDisplayCurator.hpp
=> Add sound to vehicle crew checkbox

addons/context_menu/initKeybinds.sqf
=> Prevent opening context menu using keybind while searching

addons/ai/functions/fnc_waypointParadrop.sqf, addons/ai/stringtable.xml, addons/attributes/CfgWaypointTypes.hpp, addons/attributes/functions/fnc_compileWaypoints.sqf
- Add scripted paradrop waypoint
=> Add paradrop waypoint

addons/music/CfgMusic.hpp
- Cleanup tabs in music component `CfgMusic.hpp`
=> Cleanup tabs in music component

addons/remote_control/functions/fnc_start.sqf
=> Move camera to unit's position when exiting remote control

addons/modules/functions/fnc_moduleCreateMinefield.sqf, addons/modules/stringtable.xml
=> Add random placement parameter to Create Minefield module

addons/modules/functions/fnc_moduleCreateMinefield.sqf
- Increase mine spacing at low densities (unchanged for very high density), close #148
=> Create Minefield module - Increase mine spacing at low densities

addons/context_actions/CfgContext.hpp, addons/context_actions/functions/fnc_setStance.sqf
=> Add alive check to stance context menu action

addons/common/XEH_PREP.hpp, addons/common/functions/fnc_deployCountermeasures.sqf, addons/editor/initKeybinds.sqf, addons/editor/stringtable.xml
- Add "Deploy Countermeasures" keybind, Close #116 
- Makes all currently selected vehicles deploy smokes/flares
- Prevent activating other keybinds while searching
=> Add Deploy Countermeasures keybind

addons/common/XEH_PREP.hpp, addons/common/XEH_postInit.sqf, addons/common/functions/fnc_earthquake.sqf, addons/modules/XEH_postInit.sqf, addons/modules/functions/fnc_moduleEarthquake.sqf
- Add `zen_common_fnc_earthquake` - unscheduled equivalent of `BIS_fnc_earthquake`
- Use this new function for the Earthquake module
=> Add unscheduled earthquake function

addons/common/XEH_postInit.sqf, addons/modules/CfgVehicles.hpp, addons/modules/XEH_PREP.hpp, addons/modules/config.cpp, addons/modules/functions/fnc_moduleToggleIRLasers.sqf, addons/modules/stringtable.xml
- Add module to toggle (and add) IR lasers to infantry units
=> Add Toggle IR Lasers module

addons/context_actions/CfgContext.hpp, addons/context_actions/functions/fnc_healUnits.sqf, addons/context_actions/script_component.hpp, addons/modules/CfgFactionClasses.hpp, addons/modules/stringtable.xml
- Add the medical cross icon to heal action children
- Move the player child action up
- Move main action condition to the All action
- Actions in context menu don't show if they have no children and an empty statement
- Use vanilla string for "AI"
=> Add icons to heal children actions, Move player action up

addons/garage/XEH_preInit.sqf, addons/garage/functions/fnc_onMouseZChanged.sqf
- Change the garage to open at max camera distance the first time it is opened
=> Initially open garage at max distance

addons/modules/functions/fnc_moduleFireMission.sqf
- Fix issue where module would result in a false out-of-range error
- `getArtilleryETA` should take AGL instead of ASL
=> Fix incorrect position format in moduleFireMission

addons/common/XEH_postInit.sqf, addons/modules/functions/fnc_gui_setDate.sqf
- Fix year change not correctly synchronizing with connected clients, works fine for JIP
=> Fix Set Date module year synchronization

addons/modules/functions/fnc_gui_ambientFlyby.sqf
- title, https://github.com/zen-mod/ZEN/issues/165#issuecomment-533880549
=> Add selection saving to Ambient Flyby dialog

addons/modules/functions/fnc_gui_editableObjects.sqf
=> Add selection saving to Update Editable Objects dialog

addons/context_actions/CfgContext.hpp, addons/context_actions/XEH_preInit.sqf
=> Add context menu actions to copy/paste vehicle appearance

addons/garage/functions/fnc_showVehicleInfo.sqf
=> Fix hidden garage DLC icon showing when interface is toggled

addons/context_actions/CfgEventHandlers.hpp, addons/context_actions/XEH_postInit.sqf
=> Remove unused postInit from context_actions

docs/_sidebar.md, docs/custom_waypoints.md
=> Add custom waypoints framework documentation

addons/editor/functions/fnc_handleObjectPlaced.sqf, addons/editor/functions/fnc_initDisplayCurator.sqf
=> Fix include crew toggle to work with the recent tree

addons/garage/XEH_PREP.hpp, addons/garage/functions/fnc_onMouseButtonClick.sqf, addons/garage/gui.hpp
- Add ability to toggle garage interface by right clicking and showing hidden interface by left clicking
=> Allow toggling garage interface using mouse buttons

addons/attributes/stringtable.xml
- Change the English strings for two keys (very minor changes)
Should the key IDs be updated as well?
=> Adjusted wording for attribute strings

.github/workflows/translations.yml, tools/deploy.py, tools/stringtablediag.py
- Add CI workflow to update issue with translation status
- Based off acemod/ACE3#7208
=> Add translations CI workflow

addons/modules/functions/fnc_gui_sideRelations.sqf, addons/modules/functions/fnc_moduleSideRelations.sqf
=> Add selection saving to Side Relations dialog

docs/_sidebar.md, docs/coding_guidelines.md, docs/index.html
- Add coding guidelines documentation
- For the most part same as ACE3's, with some tweaks
=> Add coding guidelines documentation

addons/modules/stringtable.xml, docs/modules_list.md
=> Add missing modules documentation

addons/context_actions/CfgContext.hpp, addons/garage/XEH_PREP.hpp, addons/garage/functions/fnc_applyToAll.sqf, addons/garage/gui.hpp, addons/garage/stringtable.xml
=> Add garage button to apply customization to all selected vehicles

addons/ai/functions/fnc_waypointFastrope.sqf, addons/ai/stringtable.xml, addons/attributes/CfgWaypointTypes.hpp
- Add scripted fastrope waypoint (requires `ace_fastroping`)
=> Add fastrope waypoint

addons/modules/functions/fnc_moduleAttachTo.sqf
- title, use `attachedTo` command
=> Improve Attach To module detaching

addons/garage/functions/fnc_openGarage.sqf, addons/garage/gui.hpp, addons/garage/script_component.hpp, addons/garage/stringtable.xml
=> Disable Apply To All button when no other vehicles are selected

AUTHORS.txt
- Add missing core team members to authors.txt
=> Update core team authors

addons/modules/functions/fnc_gui_editableObjects.sqf, addons/modules/functions/fnc_gui_globalHint.sqf, addons/modules/functions/fnc_gui_setDate.sqf
=> Remove unused _logic variable from module dialog functions

addons/modules/CfgVehicles.hpp
=> Add portrait entry for CAS modules

addons/common/XEH_preInit.sqf, addons/common/functions/fnc_healUnit.sqf
=> Fix healUnit function for ace_medical changes

docs/_404.md, docs/assets/styles.css, docs/index.html
=> Add 404 page to documentation

addons/ai/stringtable.xml, addons/area_markers/stringtable.xml, addons/attributes/stringtable.xml
=> Portuguese translation ai, area_markers, attributes

addons/dialog/functions/fnc_gui_owners.sqf, addons/doors/functions/fnc_getDoors.sqf, addons/garage/functions/fnc_populateLists.sqf, addons/inventory/functions/fnc_fillList.sqf, addons/main/script_mod.hpp
- Title; replaced `find` to check if a substring exists with updated `in` syntax.
=> Replace find substring exists check with new in syntax

addons/vision/RscTitles.hpp
=> Fix vision modes hint overlap with clock

addons/editor/functions/fnc_initDisplayCurator.sqf
- title, same as with custom search bar
=> Add right click to clear to engine search bar

Makefile, meta.cpp, tools/make.py
- title, [reference](https://community.bistudio.com/wiki/How_to_enable_Steam_Workshop_support_in_Server_Browser)
=> Add meta.cpp file, steam workshop support

addons/garage/stringtable.xml
=> Remove a duplicate stringtable entry in garage

README.md, docs/assets/styles.css, docs/development/coding_guidelines.md, docs/frameworks/context_menu.md, docs/frameworks/custom_modules.md, docs/frameworks/public_events.md
- Tweak documentation styling, mainly changing to a darker foreground color
- Some minor fixes/changes to content
=> Various changes to documentation styling

addons/context_menu/XEH_PREP.hpp, addons/context_menu/functions/fnc_removeAction.sqf, docs/frameworks/context_menu.md
=> Add function to remove context menu actions

azure-pipelines.yml, tools/stringtable_validator.py
- Add tool to validate stringtables
- Performs basic style and duplication checking
<details>
<summary>Output Example</summary>
```
Validating Stringtables
-----------------------
Checking addons\ai\stringtable.xml:
No errors found.
Checking addons\area_markers\stringtable.xml:
No errors found.
Checking addons\attributes\stringtable.xml:
No errors found.
Checking addons\camera\stringtable.xml:
No errors found.
Checking addons\common\stringtable.xml:
ERROR: Invalid name attribute 'something' for Project tag, must be 'ZEN'.
ERROR: Key 'STR_ZEN_NotCommon_Category' does not have a valid ID attribute, should be in format STR_ZEN_Common_{name}.
ERROR: Key 'STR_ZEN_NotCommon_Category' does not have its English translation listed first.
ERROR: Key …
```
=> Add stringtable validation tool

addons/common/XEH_postInit.sqf
=> Fix drawIcon3D icons being hidden after using VA

addons/garage/XEH_preInit.sqf, addons/garage/functions/fnc_onKeyDown.sqf, addons/garage/functions/fnc_onMouseButtonClick.sqf, addons/garage/functions/fnc_onTabSelect.sqf, addons/garage/functions/fnc_openGarage.sqf, addons/garage/functions/fnc_populateLists.sqf, addons/garage/gui.hpp
- Garage reopens with previously selected tab
- Selected tab can be deselected by clicking the button again or left clicking
- Allow using `TAB` key to cycle between tabs
=> Improve garage tabs handling

addons/modules/functions/fnc_moduleSpawnReinforcements.sqf
=> Fix adding reinforcements to editable objects

tools/stringtable_validator.py
- Check files (and print output) in alphabetical order
- Fix printing file error count when parsing failed
- Improve wording on multiple keys error
=> Stringtable validator improvements

azure-pipelines.yml, tools/sqf_validator.py
- Add SQF validator tool from ACE3
- Cleaned up code and improved error descriptions
- Removed `#` handling, resulted in improper counting of brackets in multi-line defines
=> Add SQF Validator

addons/garage/functions/fnc_closeGarage.sqf
=> Fix drawIcon3D icons being hidden after using garage

docs/user_guide/context_actions.md, tools/sqf_validator.py
- Fix undefined variable in SQF validator
- Fix header in context actions docs
=> Fix sqf validator and context actions docs header

tools/stringtable_validator.py
- title, same as acemod/ACE3#7332
=> Stringtable Validator - Check for tabs and correct spacing

addons/editor/initKeybinds.sqf, addons/editor/stringtable.xml
- Add keybind to set focus to the search bar
=> Add Focus Search Bar keybind

addons/editor/functions/fnc_handleLoad.sqf
=> Improve tree collapse and declutter compatibility for ZGM missions

addons/modules/functions/fnc_gui_spawnReinforcements.sqf
=> Fix reinforcement group count when deleting by double clicking

AUTHORS.txt, addons/modules/functions/fnc_gui_ambientFlyby.sqf, addons/modules/functions/fnc_moduleAmbientFlyby.sqf
- Use `sizeOf` command to determine spawn offset - better handles very large aircraft
- `disableAI` and `setSkill` of all crew
- Increase default distance to 5000
=> Improve Ambient Flyby module spawn offset

addons/modules/functions/fnc_addTeleporterAction.sqf, addons/modules/stringtable.xml
- title, teleport unit's vehicle when not on foot
=> Add ability to teleport vehicles using Create Teleporter module

addons/camera/initSettings.sqf
- title, allow for slower camera speeds
=> Decrease minimum values for camera speed settings

addons/ai/stringtable.xml, addons/area_markers/stringtable.xml, addons/attributes/stringtable.xml, addons/camera/stringtable.xml, extras/blank/stringtable.xml
=> Add Russian translations

addons/modules/functions/fnc_addIntelAction.sqf
=> Fix intel action not adding an intel entry

addons/modules/CfgVehicles.hpp, addons/modules/functions/fnc_moduleChangeHeight.sqf, addons/modules/stringtable.xml
=> Fix decimal input for Change Height module

addons/common/functions/fnc_changeGroupSide.sqf, addons/modules/CfgVehicles.hpp, addons/modules/functions/fnc_moduleGroupSide.sqf, addons/modules/stringtable.xml
=> Add option to change group of selected unit only

addons/context_menu/functions/fnc_initDisplayCurator.sqf
=> Prevent opening context menu while select position is active

optionals/compat_ace/initSettings.sqf
=> Fix settings category for compat_ace optional

addons/editor/initKeybinds.sqf, addons/editor/initSettings.sqf, addons/editor/stringtable.xml
=> Add setting to control deep copy/paste randomization

addons/context_actions/CfgContext.hpp
=> Fix staggered column in formation context action

.github/release-drafter.yml, .github/workflows/release-drafter.yml
=> Add release drafter CI

.github/release-drafter.yml
=> Fix issue with label arrays

addons/common/stringtable.xml, addons/modules/functions/fnc_modulePatrolArea.sqf
- Add a `Careless` option to the Toolbox
- Will close #339
=> Add careless option to Patrol Area module

addons/editor/RscDisplayCurator.hpp
- Use 3DEN textures for tree scroll bars
- Use common checkbox class for vehicle crew toggle
=> Improve editor trees scroll bar visuals

addons/dialog/functions/fnc_gui_owners.sqf
- title, Close #337 
- Fix not using `lbData` to get group/player
=> Sort players alphabetically in OWNERS control

addons/common/stringtable.xml
=> Fix japanese typo

addons/modules/functions/fnc_moduleEditableObjects.sqf
=> Add Thing type objects to Editable Objects module Static filter

optionals/compat_ace/ACE_ZeusActions.hpp, optionals/compat_ace/XEH_PREP.hpp, optionals/compat_ace/XEH_preInit.sqf, optionals/compat_ace/XEH_preStart.sqf, optionals/compat_ace/config.cpp, optionals/compat_ace/functions/fnc_canRemoteControl.sqf, optionals/compat_ace/functions/fnc_remoteControl.sqf, optionals/compat_ace/functions/script_component.hpp
- title, replace ACE using BI's remote control with own
=> Use ZEN remote control in ACE interaction menu action

tools/new_component.py
- Add `new_component.py` script which takes a single argument (component name, e.g. `ai`)
- It will behave weirdly with more than one word so it isn't a catch-all solution (e.g. `area_markers`).
- You will need to manually change the contents of the `stringtable.xml`  and the beautified name in `script_component.hpp`.
- _Note_: it does a search & replace of the word `blank|Blank|BLANK` and requires a `blank` component in the `extras` directory. If your project doesn't follow those guidelines, it will require manual tweaking.
=> Create a new component easier via a Python tool

addons/modules/functions/fnc_moduleChatter.sqf
- Add name of unit to the tool box
=> Show unit name in Chatter dialog title

addons/editor/functions/fnc_addGroupIcons.sqf
=> Fix incorrect upper limit in addGroupIcons loops

addons/common/functions/fnc_deserializeObjects.sqf, addons/common/functions/fnc_serializeObjects.sqf
=> Add support for unit insignias in serializing functions

addons/attributes/initAttributes.sqf
=> Switch icon order of Engine and Lights attributes

addons/common/functions/fnc_deserializeInventory.sqf, addons/common/functions/fnc_serializeInventory.sqf
=> Preserve magazine ammo counts in serializing functions

addons/music/CfgMusic.hpp, addons/music/stringtable.xml
- Add missing music tracks from the vanilla game that came with the Old Man update.
- Make the names more consistent with the already existing entries.
=> Unlock Old Man Music

addons/modules/functions/fnc_addIntelAction.sqf, addons/modules/functions/fnc_moduleCreateIntel.sqf, addons/modules/stringtable.xml
- Add more intel classes
- Add Action sounds
=> Action sound and more classes for intel

addons/common/XEH_postInit.sqf, addons/editor/initKeybinds.sqf, addons/editor/stringtable.xml
- title, complementary to the base game one to orient to sea normal
=> Add Orient to Terrain Normal keybind

addons/music/CfgMusic.hpp
=> Fix Old Man duplicate music class

README.md
- Add the Discord badge to the README.
=> Added Discord badge to README

tools/stringtable_validator.py
=> Stringtable Validator - Print parsing error exception

addons/ai/stringtable.xml, addons/attributes/stringtable.xml, addons/camera/stringtable.xml, addons/common/stringtable.xml, addons/compositions/stringtable.xml, addons/context_actions/stringtable.xml, addons/damage/stringtable.xml, addons/editor/stringtable.xml, addons/editor_previews/stringtable.xml, addons/flashlight/stringtable.xml, addons/garage/stringtable.xml, addons/inventory/stringtable.xml, addons/loadout/stringtable.xml, addons/modules/stringtable.xml, addons/placement/stringtable.xml, addons/position_logics/stringtable.xml
- Add missing polish translations
*Note:* Some translations were left out as most of the Polish community will be more familiar with their original names of certain things
=> Add Polish translations

addons/context_actions/functions/fnc_teleportPlayers.sqf
=> Prevent collisions when teleporting players using context menu

addons/loadout/gui.hpp
- title, move search/clear buttons and search bar down a bit to match the inventory display
=> Improve loadout display positioning

addons/common/XEH_postInit.sqf
=> Remove deprecated public events

docs/assets/styles.css, docs/development/coding_guidelines.md, docs/frameworks/context_menu.md, docs/frameworks/custom_modules.md, docs/index.html, docs/user_guide/context_actions.md, docs/user_guide/modules_list.md
- title
- Update context actions and modules list documentation 
- Use `sqf` highlighting instead of `clike`
=> Various documentation updates and fixes

addons/modules/CfgVehicles.hpp, addons/modules/XEH_PREP.hpp, addons/modules/XEH_postInit.sqf, addons/modules/config.cpp, addons/modules/functions/fnc_moduleCrewToGunner.sqf, addons/modules/stringtable.xml, docs/user_guide/modules_list.md
- Add Zeus module to have existing AI crew take the place of an incapacitated gunner.
- https://youtu.be/hoyYsp3flfY
=> Add Crew To Gunner module

AUTHORS.txt, addons/ai/stringtable.xml, addons/area_markers/stringtable.xml, addons/attributes/stringtable.xml, addons/camera/stringtable.xml, addons/common/stringtable.xml, addons/compositions/stringtable.xml, addons/context_actions/stringtable.xml, addons/context_menu/stringtable.xml, addons/custom_modules/stringtable.xml, addons/damage/stringtable.xml, addons/editor/stringtable.xml
Update Korean translations on
- addons/ai/stringtable.xml
- addons/area_markers/stringtable.xml
- addons/attributes/stringtable.xml
- addons/camera/stringtable.xml
- addons/common/stringtable.xml
- addons/compositions/stringtable.xml
- addons/context_actions/stringtable.xml
- addons/context_menu/stringtable.xml
- addons/custom_modules/stringtable.xml
- addons/damage/stringtable.xml
- addons/editor/stringtable.xml
=> Update Korean translation

addons/modules/XEH_postInit.sqf, addons/modules/functions/fnc_moduleWeather.sqf, addons/modules/stringtable.xml
- Add option to control if weather changes are forced using `forceWeatherChange`
- Close #277
=> Add forced option to Change Weather module

addons/main/CfgSettings.hpp
=> Add warning for missing ACE compatibility PBO

addons/attributes/XEH_postInit.sqf, addons/attributes/initAttributes.sqf, addons/attributes/stringtable.xml
=> Add Respawn Vehicle attribute

addons/attributes/CfgWaypointTypes.hpp, addons/attributes/XEH_PREP.hpp, addons/attributes/functions/fnc_gui_loiter.sqf, addons/attributes/gui.hpp, addons/attributes/initAttributes.sqf
- Add `LOITER` waypoint type
- Add attributes to set loiter waypoint direction and radius
- Close #425
=> Add loiter waypoint type

addons/modules/functions/fnc_moduleTeleportPlayers.sqf
=> Clear previous selection in Teleport Players module

addons/context_actions/functions/fnc_teleportPlayers.sqf, addons/context_actions/functions/fnc_teleportZeus.sqf
=> Fix teleporting onto surfaces using context menu actions

addons/camera/initSettings.sqf, addons/common/initSettings.sqf, addons/context_menu/initSettings.sqf, addons/editor/initSettings.sqf, addons/editor_previews/initSettings.sqf, addons/placement/initSettings.sqf, addons/visibility/initSettings.sqf, addons/vision/initSettings.sqf, optionals/compat_ace/initSettings.sqf
=> Use public CBA_fnc_addSetting instead of internal CBA_settings_fnc_init

addons/editor/RscDisplayCurator.hpp
- title, previously was 1 pixel bigger than controls group and could be scrolled
- Extend create frame down to bottom and use a line control for the top-horizontal line
- Fixes issue with frame control not aligning properly
=> Fix include crew panel positioning

addons/modules/functions/fnc_bi_moduleCurator.sqf
- title, with a very large amount of mods the module can take a long time to be unassigned when loading in initially (from testing, as much as 50 s)
=> Remove Game Master module locality transfer fix timeout

.github/release-drafter.yml
=> Use version resolver for release drafter

.github/workflows/build.yml, .github/workflows/notify.yml
- This should allow notifications from merge requests on forked repositories.
=> Split notify job to different workflow

addons/ai/functions/fnc_waypointSearchBuilding.sqf, addons/ai/stringtable.xml, addons/attributes/CfgWaypointTypes.hpp, addons/modules/CfgVehicles.hpp, addons/modules/functions/fnc_moduleSearchBuilding.sqf, addons/modules/stringtable.xml
=> Add search building waypoint

.github/workflows/notify.yml, tools/stringtable_validator.py, tools/stringtablediag.py
- Update CI validation scripts to latest versions
- Fix notify to only trigger once
=> Several CI changes

tools/build.py
- Use HEMTT when running build.py, if it is installed.
=> Add HEMTT to build.py

addons/custom_modules/XEH_preInit.sqf, addons/custom_modules/functions/fnc_addModules.sqf, addons/editor/functions/fnc_handleLoad.sqf
- Fix custom modules not being added to modules tree in ZGM missions
=> Fix custom modules not being added in ZGM missions

addons/doors/functions/fnc_getActions.sqf
- title, `distance` expects AGL positions but we use ASL here
=> Use vectorDistance for doors max scan distance check

addons/modules/functions/fnc_bi_moduleCurator.sqf
- Fix Game Master modules being deleted in multiplayer, Close #420 
- This check is unnecessary; the rest of the code doesn't require the logic being local to the server
=> Fix Game Master modules being deleted in multiplayer

addons/pylons/functions/fnc_configure.sqf
- Sort pylon magazines alphabetically while keeping the empty option at the top
=> Sort pylon magazine combo boxes alphabetically

addons/inventory/gui.hpp
- Fix a missing semicolon in the inventory component
=> Fix missing semicolon in gui.hpp for the inventory component

addons/common/XEH_PREP.hpp, addons/common/functions/fnc_isRemoteControlled.sqf, addons/common/functions/fnc_openArsenal.sqf
=> Fix RC breaking when entering ACE arsenal

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement-request.md, .github/ISSUE_TEMPLATE/other.md
- Disable blank issue option, we have a template for other that fits that function.
- Added some warning comments to help people understand what needs to be filled out.
- Add enhancement template
=> Update issue templates

addons/common/functions/fnc_openArsenal.sqf
=> Fix incorrect variable name in openArsenal function

addons/modules/functions/fnc_moduleToggleFlashlights.sqf
- Correctly remove NVGs of units when specified.
=> Fix variable in Flashlight Module

addons/modules/XEH_postInit.sqf, addons/modules/functions/fnc_moduleHideTerrainObjects.sqf
- title, only one server event instead of one for every object
=> Optimize Hide Terrain Objects module server events

addons/modules/functions/fnc_moduleHideTerrainObjects.sqf
- Change the radius parameter from edit box to slider 1 to 1000
- Prevents user from setting it too high and crashing their game
=> Change Hide Terrain Objects module radius option to a slider

addons/common/XEH_postInit.sqf, addons/garage/functions/fnc_applyToAll.sqf, addons/garage/functions/fnc_onAnimationSelect.sqf, addons/garage/functions/fnc_onTextureSelect.sqf
=> Fix remote vehicles not updating in garage

.github/workflows/build.yml
=> Upload build artifacts

addons/common/functions/fnc_deserializeObjects.sqf, addons/modules/functions/fnc_compileAircraft.sqf, addons/modules/functions/fnc_compileReinforcements.sqf, addons/modules/functions/fnc_gui_ambientFlyby.sqf, addons/modules/functions/fnc_gui_spawnReinforcements.sqf
- Replace the use of CBA hashes with the base game hashes. ~Currently only available on the dev branch, but the new base game hash system is definitely faster.~
=> Replace CBA hashes with base game hashes

addons/ai/stringtable.xml, addons/attributes/stringtable.xml, addons/common/stringtable.xml, addons/compositions/stringtable.xml, addons/context_actions/stringtable.xml, addons/damage/stringtable.xml, addons/doors/stringtable.xml, addons/editor/stringtable.xml, addons/editor_previews/stringtable.xml, addons/faction_filter/stringtable.xml, addons/flashlight/stringtable.xml, addons/inventory/stringtable.xml, addons/loadout/stringtable.xml, addons/modules/stringtable.xml, addons/music/stringtable.xml, addons/placement/stringtable.xml, addons/position_logics/stringtable.xml, addons/pylons/stringtable.xml, addons/tasks/stringtable.xml, addons/vision/stringtable.xml, extras/blank/stringtable.xml, optionals/compat_ace/stringtable.xml
=> Update Japanese translation

addons/common/stringtable.xml, addons/inventory/gui.hpp
=> Inventory - Fix unlocalized sort mode strings

addons/modules/CfgVehicles.hpp, addons/modules/XEH_PREP.hpp, addons/modules/config.cpp, addons/modules/functions/fnc_moduleAnimationViewer.sqf, addons/modules/stringtable.xml, docs/user_guide/modules_list.md
=> Add Show In Animation Viewer module

addons/cover_map/gui.hpp
- title, should be the last issue 😄
=> Cover Map - Fix missing semicolon

addons/editor/functions/fnc_handleLoad.sqf
- title, as highlighted by @dedmen, check if the selected item is a category by checking if it has children
=> Editor - Improve group trees deselect path check

addons/editor/functions/fnc_bi_curatorObjectPlaced.sqf
=> Fix comment style

addons/ai/stringtable.xml
- Add translations to all functions into Spanish.
=> Add Spanish translations

addons/editor/functions/fnc_handleObjectPlaced.sqf, addons/main/script_mod.hpp
- title, requires new alternative syntax for `deleteVehicleCrew` command (2.06)
=> Editor - Delete entire vehicle crew all at once

addons/editor/functions/fnc_handleObjectPlaced.sqf, addons/main/script_mod.hpp
=> Revert "Editor - Delete entire vehicle crew all at once"

addons/ai/stringtable.xml, addons/attributes/stringtable.xml, addons/common/stringtable.xml, addons/compositions/stringtable.xml, addons/context_actions/stringtable.xml, addons/context_menu/stringtable.xml, addons/cover_map/stringtable.xml, addons/doors/stringtable.xml, addons/editor/stringtable.xml, addons/flashlight/stringtable.xml, addons/inventory/stringtable.xml, addons/loadout/stringtable.xml, addons/modules/stringtable.xml, addons/pylons/functions/fnc_configure.sqf, addons/pylons/stringtable.xml, addons/remote_control/stringtable.xml, addons/tasks/CfgTaskTypes.hpp, addons/tasks/stringtable.xml
- Port translations from Achilles
- Update French and German
- Replace `CfgTaskTypes` entries with Vanilla localizations if possible.
=> Update translations (mainly French and German)

addons/common/XEH_postInit.sqf, addons/common/stringtable.xml, addons/modules/CfgVehicles.hpp, addons/modules/XEH_PREP.hpp, addons/modules/XEH_postInit.sqf, addons/modules/config.cpp, addons/modules/functions/fnc_moduleScaleObject.sqf, addons/modules/script_component.hpp, addons/modules/stringtable.xml
- Add module for scaling objects (restricted to attached objects)
=> Add Scale Object module

addons/tasks/CfgTaskTypes.hpp, addons/tasks/stringtable.xml
- title, use "Attack" instead of "Assault" and "Scout" instead of "Recon"
=> Tasks - Fix task type translations

addons/ai/stringtable.xml, addons/area_markers/stringtable.xml, addons/attributes/stringtable.xml, addons/camera/stringtable.xml, addons/common/stringtable.xml, addons/compositions/stringtable.xml, addons/context_actions/stringtable.xml, addons/context_menu/stringtable.xml, addons/cover_map/stringtable.xml, addons/custom_modules/stringtable.xml, addons/damage/stringtable.xml, addons/doors/stringtable.xml, addons/editor/stringtable.xml, addons/editor_previews/stringtable.xml, addons/faction_filter/stringtable.xml, addons/flashlight/stringtable.xml, addons/garage/stringtable.xml, addons/inventory/stringtable.xml, addons/loadout/stringtable.xml, addons/modules/stringtable.xml, addons/placement/stringtable.xml, addons/position_logics/stringtable.xml, addons/pylons/stringtable.xml, addons/remote_control/stringtable.xml, addons/tasks/stringtable.xml, addons/visibility/stringtable.xml, addons/vision/stringtable.xml
Add Chinese translation (Simplified and Traditional Chinese) for all stringtable.xml.
=> Add Chinese translation

addons/common/functions/fnc_selectPosition.sqf
- Fix undefined variable (the callback).
=> Fix undefined variable in selectPosition function

addons/context_actions/functions/fnc_canEditInventory.sqf, addons/inventory/XEH_preInit.sqf, addons/inventory/functions/fnc_configure.sqf, addons/main/script_mod.hpp
- title, makes inventory display account for load set by `setMaxLoad` command
=> Inventory - Use maxLoad command

addons/modules/functions/fnc_moduleTeleportPlayers.sqf, addons/modules/script_component.hpp
- Arrange players in a grid centered at the target position.
=> Improve positioning of Teleport Players module

addons/context_actions/functions/fnc_canEditInventory.sqf, addons/inventory/XEH_preInit.sqf
- title, for some reason `maxLoad player` is > 0
=> Inventory - Disable for CAManBase objects

addons/editor/functions/fnc_handleObjectPlaced.sqf
=> Mark created groups for autodeletion

addons/editor/functions/fnc_handleObjectPlaced.sqf, addons/placement/functions/fnc_handleObjectPlaced.sqf
- If crewed aircraft is placed using the map, at a position that is over water or outside of the map, spawn it flying
- Useful for inbound AI aircraft
- https://www.youtube.com/watch?v=g5gi_wUOeA8
=> Editor - Improve placing aircraft in map

addons/attached_objects/functions/fnc_handleObjectEdited.sqf
- Fix attached objects rotation
=> Fix attached object rotation

addons/modules/functions/fnc_moduleSuppressiveFire.sqf
=> Fix Suppressive Fire module fire mode string

addons/common/functions/fnc_canFire.sqf, addons/common/functions/fnc_fireWeapon.sqf
- Laserdesignator_mounted fires but cycles too quickly to reliably turn to desired state
- Add firing delay time check
- https://www.youtube.com/watch?v=LMWf6TOveJE
=> Fix laser cycling too quickly

addons/area_markers/CfgContext.hpp, addons/area_markers/functions/fnc_module.sqf
=> Area Markers - Fix module and context menu action

addons/attributes/initAttributes.sqf
- Check `fuelCapacity` config for Engine attribute
- Check `class Reflectors` config for Lights attribute
=> Improve conditions for Engine and Lights attributes

addons/attributes/CfgWaypointTypes.hpp, addons/attributes/functions/fnc_compileWaypoints.sqf, addons/attributes/functions/fnc_gui_waypoint.sqf, addons/attributes/gui.hpp, docs/frameworks/custom_waypoints.md
- title, make use of it for the ACE fastroping waypoint
- Useful for #700
=> Add support for waypoint type conditions and priority

addons/modules/CfgVehicles.hpp
- ![image](https://user-images.githubusercontent.com/11483210/229021160-9d52ac4b-5def-4b7e-b18c-793de9087672.png)
=> Add icon for Scale Object module

addons/context_actions/CfgContext.hpp, addons/context_actions/stringtable.xml
- Add Context Action Editable Objects > Remove > Selected
=> Add Editable Objects > Remove > Selected context menu action

addons/context_menu/functions/fnc_initDisplayCurator.sqf, addons/main/script_mod.hpp
=> Context Menu - Use setCuratorSelected

addons/modules/XEH_postInit.sqf
- Fix Hide Terrain Objects module needing large radius to capture tall objects
=> Fix Hide Terrain Objects module for tall objects

README.md
=> Replace hard-coded version shield in README

addons/common/functions/fnc_changeGroupSide.sqf
- Same problem as https://github.com/acemod/ACE3/pull/9388, applied same solution.
=> Modules - Fix Change Side module

addons/common/functions/fnc_exportMissionSQF.sqf
- Took information from the wiki page and applied it: https://community.bistudio.com/wiki/createMarker
- Set `type` immediately after marker creation.
- Create marker locally, do all changes locally, then when ready broadcast the marker globally.
=> Common - Optimise marker global broadcast for exporting SQF

addons/area_markers/functions/fnc_onMouseButtonDown.sqf
- title, when marker moving is started, cancel placement
=> Area Markers - Cancel placement when an icon is clicked

addons/common/functions/fnc_exportMissionSQF.sqf
=> Common - Fix Export Mission SQF not saving formation direction

addons/music/stringtable.xml
Missing Stringtable Entry
fixes #780
=> Music - Fix missing stringtable entry

README.md, docs/development/coding_guidelines.md, docs/home.md, tools/deploy.py
- Redirect users to the new ACE3 webpages
=> Docs - Fix ACE3 webpage links

.github/workflows/arma.yml
- Fix upload-artifact is deprecated
=> Tools - Fix upload-artifact is deprecated

.github/workflows/release-drafter.yml
- Update release-drafter
This should not have breaking changes.
=> Tools - Update release-drafter

addons/area_markers/stringtable.xml, addons/attached_objects/stringtable.xml, addons/attributes/stringtable.xml, addons/building_markers/stringtable.xml, addons/compat_ace/stringtable.xml, addons/compat_advanced_rappelling/stringtable.xml, addons/context_actions/stringtable.xml, addons/editor/stringtable.xml, addons/modules/stringtable.xml, addons/visibility/stringtable.xml
- Add missing localization for Simplified Chinese
=> Translations - Improve Simplified Chinese
