zen-mod/ZEN

addons/editor/functions/fnc_bi_curatorObjectPlaced.sqf

- title, for QOL since placing other objects does not show attributes

Do not auto show ammo box attributes for QOL

---

addons/context_menu/functions/fnc_openMenu.sqf

- Consistently open context menu for one man groups when the unit is hovered versus selected, fix #20 
- For QOL, add units from a hovered group to the selected units array as if the unit was selected and then the menu was opened

Consistently open context menu for hovered and selected entities

---

addons/attributes/CfgEventHandlers.hpp
addons/attributes/RscAttributes.hpp
addons/attributes/XEH_PREP.hpp
addons/attributes/XEH_postInit.sqf
addons/attributes/config.cpp
addons/attributes/functions/fnc_buttonSkills.sqf
addons/attributes/functions/fnc_initAttributesDisplay.sqf
addons/attributes/stringtable.xml
addons/dialog/functions/fnc_create.sqf
addons/dialog/functions/fnc_gui_slider.sqf
addons/dialog/gui.hpp
addons/garage/RscAttributes.hpp
addons/inventory/RscAttributes.hpp
docs/dynamic_dialog.md

- Add skills button to unit and group attributes displays to allow for fine-tuning of AI sub-skills
- Add `SLIDER:PERCENT` sub-type to the slider dialog control

Add skills button to attributes displays

---

addons/dialog/functions/fnc_create.sqf
addons/dialog/functions/fnc_gui_edit.sqf
addons/dialog/gui.hpp
docs/dynamic_dialog.md

- Add `EDIT:MULTI` and `EDIT:CODE` multi-line edit box sub-types to dialog
- Close #48

Add multi-line edit box control types

---

addons/context_menu/functions/fnc_createContextGroup.sqf

- Do not close the context menu when the user clicks an empty action
- Will help with actions that are only there to categorize others (stance, formation, etc.)
- This is the behaviour of the 3DEN context menu

Keep context menu open if clicked action does nothing

---

addons/attributes/RscAttributes.hpp
addons/attributes/XEH_PREP.hpp
addons/attributes/XEH_postInit.sqf
addons/attributes/functions/fnc_buttonSensors.sqf
addons/attributes/functions/fnc_buttonSkills.sqf
addons/attributes/stringtable.xml

- Add sensors button to vehicle attributes displays to control vehicle data link capabilities

Add sensors button to attributes displays

---

addons/context_menu/functions/fnc_createContextGroup.sqf

- Offset the context menu opening position one pixel right, one pixel down so that an action is not selected by default
- Close #72

Offset context menu opening position

---

addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf
addons/modules/functions/fnc_gui_cas.sqf
addons/modules/functions/fnc_gui_executeCode.sqf

- Disable attributes display for execute code module when used in JIP mode
- Fix #64

Disable attributes for JIP execute code module

---

addons/doors/functions/fnc_module.sqf

- title, when attached to a non-building and a building is not nearby, displayed hint will be `NoBuilding` instead of `NoDoors`
- Also triggers nearby search when attached object is not a building

Improve doors module hint when attached

---

addons/context_actions/functions/fnc_teleportZeus.sqf

- Use `_hoveredEntity` instead of `curatorMouseOver` for Teleport Zeus action
- `curatorMouseOver` can change while `_hoveredEntity` will remain as the entity from when the menu was opened

Use hovered entity for teleport Zeus

---

addons/common/XEH_PREP.hpp
addons/common/XEH_postInit.sqf
addons/common/functions/fnc_ejectPassengers.sqf
addons/editor/initKeybinds.sqf
addons/editor/stringtable.xml

- Add "Eject Passengers" keybind
- Unlike the vanilla eject keybind, only ejects cargo units and not immediately
- Units ejected from flying aircraft are given parachutes

Add Eject Passengers keybind

---

addons/custom_modules/CfgFactionClasses.hpp
addons/custom_modules/CfgVehicles.hpp
addons/custom_modules/config.cpp
addons/custom_modules/functions/fnc_addModules.sqf

- title, when addons are changed while interface is open
- `scopeCurator` does  not need to be `2` for the modules to show up in recent tree, just need to be in `CfgPatches` units array

Fix custom modules category showing when curator addons are changed

---

addons/modules/XEH_postInit.sqf
addons/modules/functions/fnc_moduleFireMission.sqf

- title, Fix #99 
- Fire each round individually at a random position around the center
- Rounds are not fired as fast but produces the correct behaviour that "spread" implies

Fix artillery fire mission spread behaviour

---

addons/common/stringtable.xml
addons/modules/CfgVehicles.hpp
addons/modules/XEH_PREP.hpp
addons/modules/XEH_postInit.sqf
addons/modules/config.cpp
addons/modules/functions/fnc_addTeleporterAction.sqf
addons/modules/functions/fnc_moduleCreateTeleporter.sqf
addons/modules/functions/fnc_moduleCreateTeleporterServer.sqf
addons/modules/script_component.hpp
addons/modules/stringtable.xml
docs/modules_list.md

Add create teleporter module

---

addons/area_markers/$PBOPREFIX$
addons/area_markers/CfgContext.hpp
addons/area_markers/CfgEventHandlers.hpp
addons/area_markers/CfgVehicles.hpp
addons/area_markers/XEH_PREP.hpp
addons/area_markers/XEH_postInit.sqf
addons/area_markers/XEH_preInit.sqf
addons/area_markers/XEH_preStart.sqf
addons/area_markers/config.cpp
addons/area_markers/functions/fnc_applyProperties.sqf
addons/area_markers/functions/fnc_configure.sqf
addons/area_markers/functions/fnc_createIcon.sqf
addons/area_markers/functions/fnc_deleteIcon.sqf
addons/area_markers/functions/fnc_module.sqf
addons/area_markers/functions/fnc_onKeyDown.sqf
addons/area_markers/functions/fnc_onMouseButtonDown.sqf
addons/area_markers/functions/fnc_onMouseButtonUp.sqf
addons/area_markers/functions/fnc_onMouseDblClick.sqf
addons/area_markers/functions/fnc_onMouseMoving.sqf
addons/area_markers/functions/fnc_setIconAngle.sqf
addons/area_markers/functions/fnc_setIconColor.sqf
addons/area_markers/functions/fnc_update.sqf
addons/area_markers/functions/script_component.hpp
addons/area_markers/gui.hpp
addons/area_markers/script_component.hpp
addons/area_markers/stringtable.xml
addons/common/functions/fnc_initSliderEdit.sqf
addons/main/script_macros.hpp
addons/modules/script_component.hpp

- Add ability to create area markers with Zeus
- Can be created by either using the module or context menu on the map
- Can be moved around by clicking on the center icon and dragging
- Properties can be edited by double clicking on the center icon
- Can be deleted by hovering over the center icon and pressing delete key
- One small annoyance is pressing escape to close the configure menu also closes the map
- No workaround, hard coded engine behaviour (ignores handled KeyDown EH)
- Can't manually use `ctrlShow` on the map control either
- Improve `initSliderEdit` common function with support for percentage sliders and CODE as formatting parameter
<details>
</details>

Add Area Markers

---

addons/context_menu/XEH_PREP.hpp
addons/context_menu/functions/fnc_addAction.sqf
addons/context_menu/functions/fnc_compileActions.sqf
addons/context_menu/functions/fnc_createAction.sqf
addons/context_menu/functions/fnc_createContextGroup.sqf
addons/context_menu/functions/fnc_getActiveActions.sqf
addons/context_menu/functions/fnc_openMenu.sqf
addons/context_menu/script_component.hpp
docs/context_menu.md
docs/custom_modules.md
docs/public_events.md

- Add dynamic children actions support for the context menu
- Add support for custom action arguments which are available in the action's code blocks
- Add modifier function that allows for dynamically modifying an action when the menu is opened
- Only actions that don't have an empty statement or have active children will be shown now
- Removes need to duplicate checks inside of children actions into the parent action to hide it if children are inactive
- Move active actions checking outside of `createContextGroup`
- Now active actions are only collected once (when opening)
- Backwards incompatible change for adding actions through script (config will stay the same)
**Todo:**

Context menu support for dynamic children actions

---

addons/common/XEH_PREP.hpp
addons/common/functions/fnc_isInScreenshotMode.sqf
addons/visibility/functions/fnc_draw.sqf
addons/visibility/initSettings.sqf
addons/visibility/stringtable.xml

- Move setting out of subcategory and change default to false
- Was the only setting in the subcategory
- Seems more users will have it turned off
- Disable drawing while the interface is in screenshot mode
- Add `isInScreenshotMode` common function
- Move the "VISIBLE" text closer to the cursor (less vertical space)
- Don't draw an indicator for the local player (thoughts?)

Visibility indicator tweaks

---

addons/common/functions/fnc_initSliderEdit.sqf

- Fix `initSliderEdit` not dividing percentage input by 100 due to missing `_isPercentage` variable

Fix initSliderEdit not dividing percentage input

---

addons/modules/CfgVehicles.hpp

- title, module will have the smoke pillar icon when placed in the world instead of being empty

Add portrait entry for Smoke Pillar module

---

addons/editor/functions/fnc_handleTreeButtons.sqf

- title, fix annoying behaviour resulting from having to expand the useless "side" node of group trees to view available factions
- technically, the group trees are not fully collapsed after this change but I think most users will prefer this behaviour

Keep factions visible when clicking the collapse all button

---

addons/common/XEH_postInit.sqf

- title, VA sets the `curatorCamera`'s position and `vectorDir` to the arsenal camera's but does not handle `vectorUp`

Fix VA incorrectly changing Zeus camera position

---

addons/common/functions/fnc_isPlacementActive.sqf

- Simply `isPlacementActive` by getting rid of duplicate code from `getActiveTree`

Improve isPlacementActive common function

---

addons/common/XEH_PREP.hpp
addons/common/functions/fnc_getDLC.sqf
addons/common/functions/fnc_getSideIcon.sqf
addons/garage/functions/fnc_showVehicleInfo.sqf
addons/garage/script_component.hpp

Move garage GETDLC macro to common function

---

addons/modules/functions/fnc_moduleAmbientAnimEnd.sqf

- title, switch unit to death animation instead of animation reset

Improve ambient animation handling of dead units

---

addons/editor/functions/fnc_handleObjectPlaced.sqf
addons/editor/functions/fnc_initDisplayCurator.sqf
addons/editor/initKeybinds.sqf
addons/editor/stringtable.xml

- Add keybind to toggle visibility of editable icons
- Unlike the vanilla "Collapse / Expand Section" keybind:
- Does not require focus to be on the entities tree
- Hides all icons, not just a section

Add Toggle Editable Icons keybind

---

addons/common/XEH_postInit.sqf
addons/editor/CfgFunctions.hpp
addons/editor/functions/fnc_bi_curatorObjectEdited.sqf
addons/editor/initSettings.sqf
addons/editor/stringtable.xml

- Improve `BIS_fnc_curatorObjectEdited` by:
- Add support for loading/unloading vehicle in vehicle cargo
- Improving handling of slingloaded objects
- Properly handle situation where object is already slingloaded
- Object will detach if moved (without having to hover over another object)
- Use `setVehiclePosition` when moving objects to ground level
- Performs check for collisions with other objects
- Cleaning up code
- Add `zen_editor_parachuteSounds` setting
- Controls whether jet flyby sounds are played when objects are given parachutes

Improve object editing (vehicle in vehicle cargo, jet sounds setting)

---

addons/editor/functions/fnc_initDisplayCurator.sqf

- Fix selecting a non-placement path in group trees preventing the selection of editable icons using left click
- This makes the group trees match the behaviour of other trees by allowing selection to still occur
- Without this, path has to be deselected by either right clicking or selecting an entity using a selection box

Fix group trees preventing editable icon selection

---

README.md
addons/editor_previews/$PBOPREFIX$
addons/editor_previews/CfgEventHandlers.hpp
addons/editor_previews/XEH_PREP.hpp
addons/editor_previews/XEH_postInit.sqf
addons/editor_previews/XEH_preInit.sqf
addons/editor_previews/XEH_preStart.sqf
addons/editor_previews/config.cpp
addons/editor_previews/functions/fnc_handleMouseExit.sqf
addons/editor_previews/functions/fnc_handleMouseUpdate.sqf
addons/editor_previews/functions/fnc_initDisplayCurator.sqf
addons/editor_previews/functions/script_component.hpp
addons/editor_previews/gui.hpp
addons/editor_previews/initSettings.sqf
addons/editor_previews/script_component.hpp
addons/editor_previews/stringtable.xml
docs/home.md

- Add object editor preview images displaying (like 3DEN) when an item is hovered in object trees
- Can be disabled through the setting
<details>
</details>

Add editor preview images displaying

---

addons/context_actions/CfgContext.hpp

- Use `serializeInventory`/`deserializeInventory` functions, these will correctly copy sub-containers

Improve inventory copy/paste context menu actions

---

addons/editor_previews/functions/fnc_handleMouseUpdate.sqf

- title, hide editor preview when going from hovering an item with a preview image to one with none

Fix editor preview hiding for items with no preview image

---

addons/ai/functions/fnc_waypointParadrop.sqf
addons/modules/functions/fnc_moduleSpawnReinforcements.sqf

- title, SAD waypoint makes aircraft slow down when approaching previous waypoint, adding the SAD waypoint after the insertion one completes seems like the most reliable way to avoid this issue
- Close #262

Fix paradrop waypoint for Spawn Reinforcements module

---

addons/ai/functions/fnc_waypointFastrope.sqf

- Set `_createDeploymentGroup` param for `ace_fastroping_fnc_deployAI` to false to prevent deletion of RP waypoint, Close #283

Fix fastrope waypoint removing reinforcements RP waypoint

---

addons/ai/functions/fnc_waypointFastrope.sqf

- Wait until the helicopter is within 2 km of waypoint before adjusting its fly height
- Previously, helicopters that started far away from waypoint would fly the entire distance at the fastrope height

Improve fastrope waypoint fly height adjustment

---

addons/markers_tree/RscDisplayCurator.hpp

- title, makes, for example, flag markers shown in color instead of black when selected

Improve markers tree selected picture color

---

addons/modules/functions/fnc_gui_executeCode.sqf

- title, execute `setName` on all clients
- Use CBA events instead of `remoteExec`

Fix displaying Execute Code module's JIP ID

---

addons/modules/functions/fnc_gui_spawnReinforcements.sqf

- Fix combo changing to paradrop unexpectedly when changing from fastrope capable vehicle to one that is not
- Switch to landing if fastroping is not available for new vehicle

Fix reinforcements insertion method combo selection

---

addons/ai/functions/fnc_waypointFastrope.sqf
addons/ai/functions/fnc_waypointLand.sqf
addons/ai/functions/fnc_waypointParadrop.sqf

- Decrease `FASTROPE_HEIGHT` from 25 to 15 - AI hover several meters higher than the set `flyInHeight`, Close #302 
- Improve handling when the waypoint's height is not on ground level (for example, on top of a building)
- Set the `flyInHeight` to 100 after fastroping is complete

Improve fastrope waypoint height handling

---

README.md
addons/flashlight/$PBOPREFIX$
addons/flashlight/CfgEventHandlers.hpp
addons/flashlight/XEH_PREP.hpp
addons/flashlight/XEH_postInit.sqf
addons/flashlight/XEH_preInit.sqf
addons/flashlight/XEH_preStart.sqf
addons/flashlight/config.cpp
addons/flashlight/functions/fnc_toggle.sqf
addons/flashlight/functions/script_component.hpp
addons/flashlight/initKeybinds.sqf
addons/flashlight/script_component.hpp
addons/flashlight/stringtable.xml
docs/home.md

- Add `flashlight` component
- Adds a keybind to toggle a camera flashlight like the one in 3DEN

Add Camera Flashlight

---

addons/camera/initSettings.sqf
addons/camera/stringtable.xml
addons/common/initSettings.sqf
addons/common/stringtable.xml
addons/context_menu/initKeybinds.sqf
addons/context_menu/initSettings.sqf
addons/editor/initKeybinds.sqf
addons/editor/initSettings.sqf
addons/editor/stringtable.xml
addons/editor_previews/initSettings.sqf
addons/main/stringtable.xml
addons/placement/initSettings.sqf
addons/visibility/initSettings.sqf
addons/vision/initKeybinds.sqf
addons/vision/initSettings.sqf
addons/vision/stringtable.xml

- Move `editor` and `editor_previews` settings under their own subcategory - "Editor"
- Makes the settings menu a bit more organized
- Move mod display name from `common` to `main`

Move editor settings under own subcategory

---

addons/flashlight/initKeybinds.sqf

- title, caused by moving strings to `main` in #308

Fix flashlight keybind category

---

addons/modules/functions/fnc_gui_fireMission.sqf

- title, was not set to map grid when no target modules existed

Fix fire mission mode when no target modules exist

---

addons/modules/functions/fnc_moduleBindVariable.sqf
addons/modules/stringtable.xml

- title, `TOOLBOX` defaults to a number not bool
- Close #325

Fix Bind Variable module broadcast option

---

addons/common/XEH_PREP.hpp
addons/common/XEH_postInit.sqf
addons/common/functions/fnc_fireArtillery.sqf
addons/common/functions/fnc_fireVLS.sqf
addons/common/functions/fnc_getArtilleryETA.sqf
addons/modules/XEH_postInit.sqf
addons/modules/functions/fnc_moduleFireMission.sqf
addons/modules/stringtable.xml

- Add ability for VLS to track moving targets, Close #320 
- Add common `fireArtillery` function
- Mostly moved code from `modules` event
- Improve artillery related functions (`fireArtillery, `fireVLS`, `getArtilleryETA`) to handle objects and map grid strings being passed as positions
- Increase low spread threshold from 10 to 25

Add ability for VLS to track targets

---

addons/placement/functions/fnc_handleObjectPlaced.sqf

- title, disable placement preview positioning when objects are placed using the map

Fix placement preview preventing placement using the map

---

addons/context_actions/functions/fnc_canHealUnits.sqf
addons/context_menu/functions/fnc_compileActions.sqf
addons/doors/functions/fnc_getState.sqf
addons/editor/functions/fnc_handleSearchClick.sqf
azure-pipelines.yml
tools/return_checker.py

- Add a python3 script that will check the file return type under these criteria:
- If docblock indicated return type is `None`:
- The last line character must be a `;`, `nil` or `};`.
- If the indicated return type is something else from `None`:
- It will emit an error with a possible fix.
- PR also fixes non-compliant files.

Add return type validator for SQF files

---

.github/release-drafter.yml

- Add colons after category titles
- Add "#" before PR numbers

Fix release drafter category titles and change template

---

addons/common/functions/fnc_deserializeObjects.sqf

- title, group had the correct side but units belonged to their original config defined one
- Close #373

Fix preserving unit sides in deserialize objects function

---

addons/dialog/functions/fnc_close.sqf

- Fix intel module causing an error on second usage after dialog rework
- After rework, the values array was the same one that was saved
- Saving a copy will prevent any issues from the values array being modified by reference (as done by the intel module)

Fix intel module, Copy dialog values when saving

---

addons/common/functions/fnc_getDefaultInventory.sqf

- title, `getDefaultInventory` did not return a copy and then the inventory display modified the cached value

Fix default inventories cache being modified by reference

---

addons/common/XEH_PREP.hpp
addons/common/functions/fnc_hasPylons.sqf
addons/pylons/$PBOPREFIX$
addons/pylons/CfgEventHandlers.hpp
addons/pylons/XEH_PREP.hpp
addons/pylons/XEH_postInit.sqf
addons/pylons/XEH_preInit.sqf
addons/pylons/XEH_preStart.sqf
addons/pylons/config.cpp
addons/pylons/functions/fnc_configure.sqf
addons/pylons/functions/fnc_handleConfirm.sqf
addons/pylons/functions/fnc_handleMagazineSelect.sqf
addons/pylons/functions/fnc_handleMirror.sqf
addons/pylons/functions/fnc_handlePreset.sqf
addons/pylons/functions/fnc_handleTurretButton.sqf
addons/pylons/functions/script_component.hpp
addons/pylons/gui.hpp
addons/pylons/script_component.hpp
addons/pylons/stringtable.xml

- Add display to configure the pylon loadouts of aircraft, Close #143 
- Correctly uses the `UIposition` config entry to ensure pylon controls are positioned on the UI picture the same as 3DEN
- Wiki says `setPylonLoadout` command is EL but from testing command seems to be AL EG
<details>
</details>

Add display to configure pylon loadouts

---

addons/context_actions/functions/fnc_teleportZeus.sqf

- title, sometimes did not work if player was in a vehicle turret

Fix Teleport Zeus context menu action when player is in a vehicle

---

addons/common/functions/fnc_fireVLS.sqf

- title, Close #415 
- Target module could be placed underground, use `createUnit` command for spread handling

Fix VLS failing to strike target module

---

addons/context_menu/functions/fnc_openMenu.sqf

- title, `_hoveredEntity` would be the waypoint's group only (not `[group, index]`) when hovering over a waypoint

Fix context menu variables when hovering over a waypoint

---

addons/common/XEH_postInit.sqf
addons/modules/functions/fnc_moduleAmbientAnimEnd.sqf
addons/modules/functions/fnc_moduleAmbientAnimStart.sqf

- title, 1 target event instead of 5 in ambient animation module start and end
- Improve common `enableAI`/`disableAI` events to handle an array of AI sections instead of just one

Optimize enableAI/disableAI target events

---

addons/modules/functions/fnc_compileAircraft.sqf

Some mods misconfigure their vehicles in such a way that causes a script error in ZEN as it only expects to see properly configured sides for public scoped vehicles. i.e. `LIB_La7_base` which has a side of 4 (Neutral)
- Fix the following script error by defaulting to civilian for unknown/weird side values.
```
3:15:26 Error in expression <call CBA_fnc_hashCreate;
_aircraftCache set [_side, _factions];
};
private _fa>
3:15:26   Error position: <set [_side, _factions];
};
private _fa>
3:15:26   Error Type Any, expected Number
3:15:26 File x\zen\addons\modules\functions\fnc_compileAircraft.sqf..., line 32
3:15:26 Error in expression <);
private _factions = _aircraftCache param [_side];
if (isNil "_factions") t>
3:15:26   Error position: <param [_side]; …
```

Fix script error for incorrectly configured aircraft

---

addons/common/functions/fnc_hasDefaultInventory.sqf

- title, use `getDefaultInventory` which correctly handles weapons/binoculars being listed under `TransportItems` class
- Nested `forEach`s look a bit weird, could use a similar comparison method as before instead of `isEqualTo` but I think this is simpler

Fix hasDefaultInventory function incorrectly handling item cargo

---

addons/attributes/functions/fnc_gui_checkboxes.sqf

- title, text font size did not match rest of dialog due to `ctrlStatic` using 3DEN pixel grid system by default

Fix attributes checkboxes control font size

---

addons/modules/functions/fnc_gui_executeCode.sqf
addons/modules/stringtable.xml

- Title, to make it the same as custom module argument order.

Switch argument order in execute code module

---

addons/ai/functions/fnc_waypointFastrope.sqf
addons/attributes/functions/fnc_bi_showCuratorAttributes.sqf
addons/attributes/functions/fnc_open.sqf
addons/attributes/initAttributes.sqf
addons/common/functions/fnc_deserializeObjects.sqf
addons/common/functions/fnc_exportMissionSQF.sqf
addons/common/functions/fnc_getPylonTurret.sqf
addons/common/functions/fnc_hasDefaultInventory.sqf
addons/context_actions/functions/fnc_canEditInventory.sqf
addons/custom_modules/functions/fnc_init.sqf
addons/damage/functions/fnc_configure.sqf
addons/doors/functions/fnc_getDoors.sqf
addons/editor/functions/fnc_bi_curatorObjectPlaced.sqf
addons/garage/functions/fnc_populateLists.sqf
addons/garage/functions/fnc_showVehicleInfo.sqf
addons/inventory/XEH_preInit.sqf
addons/inventory/functions/fnc_configure.sqf
addons/loadout/functions/fnc_configure.sqf
addons/main/script_mod.hpp
addons/modules/functions/fnc_bi_moduleMine.sqf
addons/modules/functions/fnc_gui_cas.sqf
addons/modules/functions/fnc_gui_damageBuildings.sqf
addons/modules/functions/fnc_initDisplay.sqf
addons/modules/functions/fnc_initModule.sqf
addons/modules/functions/fnc_moduleDamageBuildings.sqf
addons/pylons/functions/fnc_configure.sqf

- Use configOf that was introduced in 2.00, it is twice as fast as using typeOf in a config lookup.

use configOf instead of typeOf config lookup

---

addons/compositions/functions/fnc_buttonRandomize.sqf
addons/compositions/functions/fnc_initDisplayCurator.sqf

- title, remove duplicate code for setting color and tooltip in `initDisplayCurator`

Clean up compositions randomize button code

---

addons/doors/CfgContext.hpp
addons/doors/CfgVehicles.hpp
addons/doors/XEH_PREP.hpp
addons/doors/config.cpp
addons/doors/functions/fnc_configure.sqf
addons/doors/functions/fnc_getActions.sqf
addons/doors/functions/fnc_getState.sqf
addons/doors/functions/fnc_setState.sqf
addons/doors/functions/fnc_updatePFH.sqf
addons/doors/script_component.hpp
addons/doors/stringtable.xml
docs/user_guide/context_actions.md

- Add a context menu action that allows users to open context menu while hovering over a door and set its state
- Minor cleanup of `doors` component
<details>
</details>

Add Door State context menu action

---

addons/editor/functions/fnc_fixSideButtons.sqf
addons/editor/functions/fnc_handleLoad.sqf
addons/editor/functions/fnc_handleModeButtons.sqf
addons/editor/functions/fnc_handleSideButtons.sqf
addons/faction_filter/$PBOPREFIX$
addons/faction_filter/CfgEventHandlers.hpp
addons/faction_filter/XEH_postInit.sqf
addons/faction_filter/XEH_preInit.sqf
addons/faction_filter/XEH_preStart.sqf
addons/faction_filter/config.cpp
addons/faction_filter/script_component.hpp
addons/faction_filter/stringtable.xml

- Add `faction_filter` component
- Adds settings to control which factions (by name) are available in the unit and group trees
- Close #142 
- Fix invisible side buttons on initial load with empty trees
- Simplify code for `modeChanged` and `sideChanged` events
Works well when tested with popular asset mods. Deals with the following object categorization trickiness (for Zeus):
- `side` of `CfgFactionClasses` doesn't determine under which side an object is sorted.
- `editorCategory` can also be used to categorize an object (although generally not used for characters and vehicles).
- group compositions can have a different faction display name than objects from the same faction.
As a result, we don't use `CfgFactionClasses` directly and instead scan …

Add Faction Filter

---

addons/context_actions/CfgContext.hpp
docs/user_guide/context_actions.md

- Add Loadout>Reset context menu action which will set unit loadout to config
- Useful for when AI run out of ammo

Add Reset Loadout context menu action

---

addons/remote_control/XEH_postInit.sqf

- title, owner variable was not reset if a player disconnected while remote controlling

Fix remote control owner variable not being reset after disconnect

---

addons/modules/functions/fnc_moduleToggleLamps.sqf

- title, thanks to @veteran29 for finding this issue

Fix non-unique global event ID usage in Toggle Lamps module

---

addons/editor/initKeybinds.sqf
addons/editor/stringtable.xml

- Add a keybind to reload the Zeus interface when needed.
- Hack for #152 but not a fix

Reload Zeus Interface Keybind

---

addons/editor/initKeybinds.sqf
addons/editor/stringtable.xml

- Very minor cleanup after #542 
- Not really a hack. Standard way to reload Zeus display

Misc cleanup for reload display keybind

---

addons/common/functions/fnc_exportMissionSQF.sqf
addons/common/functions/fnc_getPylonTurret.sqf
addons/pylons/functions/fnc_configure.sqf
addons/pylons/functions/fnc_handleConfirm.sqf
addons/pylons/functions/fnc_handleMagazineSelect.sqf
addons/pylons/functions/fnc_handleTurretButton.sqf

- Improve `getPylonTurret` common function by using `getAllPylonsInfo` command (2.02)
- `setPylonLoadout` now supports `[-1]` as the driver turret
- Use `getAllPylonsInfo` for export mission SQF

Improve pylon turret functionality by using getAllPylonsInfo

---

addons/area_markers/functions/fnc_configure.sqf
addons/common/XEH_PREP.hpp
addons/common/functions/fnc_formatDegrees.sqf
addons/cover_map/$PBOPREFIX$
addons/cover_map/CfgEventHandlers.hpp
addons/cover_map/CfgVehicles.hpp
addons/cover_map/XEH_PREP.hpp
addons/cover_map/XEH_postInit.sqf
addons/cover_map/XEH_preInit.sqf
addons/cover_map/XEH_preStart.sqf
addons/cover_map/config.cpp
addons/cover_map/functions/fnc_create.sqf
addons/cover_map/functions/fnc_handleConfirm.sqf
addons/cover_map/functions/fnc_handleDelete.sqf
addons/cover_map/functions/fnc_handleDraw.sqf
addons/cover_map/functions/fnc_handleLoad.sqf
addons/cover_map/functions/fnc_handleMouseButtonDown.sqf
addons/cover_map/functions/fnc_handleMouseButtonUp.sqf
addons/cover_map/functions/fnc_handleMouseMoving.sqf
addons/cover_map/functions/fnc_handleRotationChanged.sqf
addons/cover_map/functions/fnc_remove.sqf
addons/cover_map/functions/script_component.hpp
addons/cover_map/gui.hpp
addons/cover_map/script_component.hpp
addons/cover_map/stringtable.xml
addons/modules/functions/fnc_moduleRotateObject.sqf
addons/modules/functions/fnc_moduleWeather.sqf

- Add a Zeus equivalent to the Cover Map module
- Opens a dialog with a map control where the user can draw the area on the map by left-clicking
- Close #523 
- Add common `formatDegrees` function
- Reduce code duplication between multiple components
<details>
</details>

Add Cover Map module

---

addons/cover_map/functions/fnc_handleConfirm.sqf
addons/cover_map/functions/fnc_handleDelete.sqf
addons/cover_map/functions/fnc_handleDraw.sqf
addons/cover_map/functions/fnc_handleLoad.sqf
addons/cover_map/functions/fnc_handleMouseButtonUp.sqf
addons/cover_map/functions/fnc_handleRotationChanged.sqf
addons/cover_map/gui.hpp
addons/cover_map/script_component.hpp

- title, Mikero's tools fail to build `cover_map` component due to `IDC_MAP` collision with base game includes
```
#define IDC_MAP 100
// is: 100
//was: 51
In File \x\zen\addons\cover_map\script_component.hpp: circa Line 27 #define altered without an #undef
"cover_map.pbo not produced due to error(s)" 
```

Cover Map - Fix IDC undef error

---

addons/modules/functions/fnc_compileTracers.sqf

- Use `BIS_fnc_baseWeapon` for better base weapon support
- Some weapons do not have `baseWeapon` config entry explicitly defined
- Filter out `SAFE` muzzle (generally found in RHS weapons)

Improve Tracers module weapon compatibility

---

addons/attributes/initAttributes.sqf

- title, make plate number attribute only show for vehicles that support it
- Most vehicles have `PlateInfos` defined and `name` property also set as `"spz"`
- However, vehicles that do not support plate numbers do not have the selection

Improve plate number attribute condition

---

addons/remote_control/CfgVehicles.hpp
addons/remote_control/XEH_preInit.sqf
addons/remote_control/functions/fnc_start.sqf
addons/remote_control/initSettings.sqf
addons/remote_control/script_component.hpp
addons/remote_control/stringtable.xml

- Add "Camera Exit Position" setting to control where the Zeus camera is positioned after exiting remote control
- Options are unchanged, relative, relative (limited to 50 m) [current behaviour], 10 m above unit, and 10 m behind and 10 m above unit (like vanilla remote control)
- Improve relative camera positioning options by accounting for the unit's direction

Remote Control - Add camera exit position setting

---

addons/remote_control/functions/fnc_start.sqf
docs/frameworks/public_events.md

- Add `zen_remoteControlStopped` event when remote control is stopped to complement the started event

Remote Control - Add stopped event

---

addons/modules/functions/fnc_gui_tracers.sqf
addons/modules/gui.hpp

Add mod icons to Tracers module dialog lists

---

addons/editor/functions/fnc_bi_curatorObjectPlaced.sqf

BI changed this function, we should also reflect it here.
Needed for zeus compositions to not show needless UI popups

Update BIS_fnc_curatorObjectPlaced override

---

addons/dialog/functions/fnc_create.sqf

- title, Close #615 
<details>
<summary>Test Code:</summary>
```sqf
private _options = [];
for "_i" from 1 to 20 do {
_options pushBack ["CHECKBOX", str _i, false];
};
["Example Dialog", _options, {systemChat str _this}] call zen_dialog_fnc_create;
```
</details>

Dialog - Fix issues when opened in 3DEN

---

addons/dialog/functions/fnc_gui_edit.sqf

- title, Close #617 
- Need to reposition edit box before setting its text to have it display correctly

Dialog - Fix multi-line edit box not displaying default text correctly

---

addons/attributes/initAttributes.sqf
addons/modules/functions/fnc_gui_executeCode.sqf

- Restricts code execution to logged admins when disabled with `ZEN_disableCodeExecution`

Restrict code execution to logged in admins

---

addons/context_menu/functions/fnc_getActiveActions.sqf

- title, for example, if the modifier function modified the condition, the original condition code would be used instead of the modified one

Fix context menu not using modified action data

---

addons/common/XEH_postInit.sqf
addons/modules/functions/fnc_moduleAttachTo.sqf

- Use `setVectorDirAndUp` rather than `setDir`

Fix 3D rotations for Attach To module

---

addons/attributes/stringtable.xml

Changed "Fähigkeiten" to "Fertigkeiten"
Both Abilities and Skill had the same German Translation, which made it difficult to distigush them.
I changed the STR_ZEN_Attributes_Skills to "Fertigkeiten" which is a different German translation.

Update German translation

---

addons/area_markers/XEH_PREP.hpp
addons/area_markers/XEH_postInit.sqf
addons/area_markers/XEH_preInit.sqf
addons/area_markers/functions/fnc_applyProperties.sqf
addons/area_markers/functions/fnc_configure.sqf
addons/area_markers/functions/fnc_createIcon.sqf
addons/area_markers/functions/fnc_createMarker.sqf
addons/area_markers/functions/fnc_deleteIcon.sqf
addons/area_markers/functions/fnc_initDisplayCurator.sqf
addons/area_markers/functions/fnc_isEditable.sqf
addons/area_markers/functions/fnc_onDraw.sqf
addons/area_markers/functions/fnc_onKeyDown.sqf
addons/area_markers/functions/fnc_onMapToggled.sqf
addons/area_markers/functions/fnc_onMarkerCreated.sqf
addons/area_markers/functions/fnc_onMarkerDeleted.sqf
addons/area_markers/functions/fnc_onMarkerUpdated.sqf
addons/area_markers/functions/fnc_updateIcon.sqf
addons/cover_map/XEH_postInit.sqf

- Support editing all area markers (not just those created through the module or context menu action)
- Uses the marker mission events to track markers and automatically create editable icons for them when they are area markers
- Handles 3DEN placed and scripted markers
- Markers can be blacklisted using the array (used by `cover_map` currently)
- Use an event based approach for the icon visibility instead of PFH
- A lot of edge cases but could not get it to break
- Probably minor performance improvement
- Hide icons when the the interface is hidden (screenshot mode)
- Use `HashMap`s instead of CBA namespaces

Area Markers - Support editing all area markers

---

addons/modules/XEH_postInit.sqf
addons/modules/functions/fnc_moduleWeather.sqf
addons/modules/stringtable.xml

- Addresses #681
- Adds a simple "Rain/Snow" option to the weather module.
- `QGVAR(applyWeather)` event is kept backwards compatible.
Notes:
- These changes might require some edits to the rain strength slider text, in order to be more clear:
At the moment, there is "Rain" to set the rain strength and "Precipitation" to set the type of precipitation, which makes me believe it could lead to some confusion.
Suggestions:
- Previously: "Rain" -> Suggested: "Precipitation"
- Previously: "Precipitation" -> Suggested: "Precipitation Type"
- The `rainParticles` can be changed (color, drop speed, etc., see [setRain,](https://community.bistudio.com/wiki/setRain) but I'm unsure what options should be added to the weather module. I didn't add any, as I felt …

Add snow option to Change Weather module

---

addons/common/functions/fnc_getPosFromScreen.sqf
addons/common/functions/fnc_selectPosition.sqf
addons/context_menu/script_component.hpp
addons/visibility/XEH_postInit.sqf
addons/visibility/functions/fnc_draw.sqf
addons/visibility/initSettings.sqf
addons/visibility/script_component.hpp
addons/visibility/stringtable.xml

- Add "During Placement Only" mode to visibility indicator
- Add "Max Check Distance" setting - can range from 100 to 5000 m (same as hardcoded limit of `lineIntersectsSurfaces` command)
- Improve `getPosFromScreen` common function with parameter to control whether a flat position is return or just the first intersection
- Some minor cleanup of the `visibility` component
- Close #421

Visibility - Add during placement only mode and max distance setting

---

addons/placement/XEH_postInit.sqf
addons/placement/functions/fnc_handleTreeChange.sqf

Add placement preview support to recent tree

---

addons/editor/XEH_PREP.hpp
addons/editor/functions/fnc_addModIcons.sqf
addons/editor/functions/fnc_handleLoad.sqf
addons/editor/initSettings.sqf
addons/editor/stringtable.xml

Add mod icons to create unit trees

---

addons/editor/XEH_preInit.sqf
addons/editor/functions/fnc_handleLoad.sqf
addons/placement/functions/fnc_updatePreview.sqf

- title, fix issue with `RscDisplayCurator_mousePos` unexpectedly updating when mouse is over mission controls group
Relevant code from `RscDisplayCurator.sqf`:
```sqf
//--- Mouse area
{
_ctrl = _display displayctrl _x;
_ctrl ctrladdeventhandler ["mousemoving","with (uinamespace) do {RscDisplayCurator_mousePos = [_this select 1,_this select 2];};"];
_ctrl ctrladdeventhandler ["mouseholding","with (uinamespace) do {RscDisplayCurator_mousePos = [_this select 1,_this select 2];};"];
} foreach [IDC_RSCDISPLAYCURATOR_MOUSEAREA,IDC_RSCDISPLAYCURATOR_MISSION];
```

Improve placement preview mouse position handling

---

addons/placement/functions/fnc_handleObjectPlaced.sqf
addons/placement/functions/fnc_updatePreview.sqf

- Enable rotation of placement preview when holding Zeus rotation modifier, default L Shift
- Preview rotation is preserved if Shift is released
- Object can be placed while Shift is held down
- Object rotation matches preview

Add ability to rotate placement preview objects

---

addons/common/XEH_PREP.hpp
addons/common/XEH_preInit.sqf
addons/common/functions/fnc_displayCuratorLoad.sqf
addons/common/functions/fnc_isCursorOnMouseArea.sqf
addons/common/functions/fnc_selectPosition.sqf
addons/editor/XEH_preInit.sqf
addons/editor/functions/fnc_handleLoad.sqf
addons/main/script_mod.hpp
addons/placement/functions/fnc_updatePreview.sqf

- title, mimics the behaviour of entity placement
- Close #392 
- Add `isCursorOnMouseArea` common function (maybe there is a better name)
- Move mouse position tracking from `editor` to `common`
- Requires new `ctrlAt` command from 2.12

Fix select position ignoring overlapping controls

---

addons/context_menu/functions/fnc_createContextGroup.sqf

- title, prevented selecting context menu rows with greater than the normal width

Fix width adjustment for context menu mouse area controls

---

addons/common/XEH_PREP.hpp
addons/common/XEH_postInit.sqf
addons/common/functions/fnc_deserializeObjects.sqf
addons/common/functions/fnc_updateEditableObjects.sqf
addons/context_actions/functions/fnc_openEditableObjectsDialog.sqf
addons/context_actions/functions/fnc_updateEditableObjects.sqf
addons/editor/initKeybinds.sqf
addons/editor/stringtable.xml
addons/modules/functions/fnc_moduleAmbientFlyby.sqf
addons/modules/functions/fnc_moduleCreateIntel.sqf
addons/modules/functions/fnc_moduleCreateMinefield.sqf
addons/modules/functions/fnc_moduleCreateTeleporterServer.sqf
addons/modules/functions/fnc_moduleEditableObjects.sqf
addons/modules/functions/fnc_moduleEffectFireLocal.sqf
addons/modules/functions/fnc_moduleLightSource.sqf
addons/modules/functions/fnc_moduleSitOnChair.sqf
addons/modules/functions/fnc_moduleSpawnCarrier.sqf
addons/modules/functions/fnc_moduleSpawnDestroyer.sqf
addons/modules/functions/fnc_moduleSpawnReinforcements.sqf
addons/position_logics/functions/fnc_add.sqf

- title, use case: sometimes you only want to edit a single object that is currently not editable and instead of going through the regular editable objects dialog with a small radius, this keybind provides a quick way to make the object editable (or not) by hovering over it
- Add `updateEditableObjects` objects common function
- Replaces the old `addObjects`/`removeObjects` common events
- Consolidates editable object updating in the code base to a single function

Add Toggle Object Editability keybind

---

addons/common/XEH_PREP.hpp
addons/common/XEH_postInit.sqf
addons/common/functions/fnc_forceWatch.sqf
addons/editor/initKeybinds.sqf

- title, locks vehicle turret cameras to the target to make the watch command have better targeting
- Also use `doTarget` when the target is given as an object (instead of position) - makes infantry raise their weapons without needing to be in combat mode

Improve Watch Cursor and Watch Curator Camera keybinds

---

addons/common/XEH_PREP.hpp
addons/common/XEH_postInit.sqf
addons/common/functions/fnc_setVehicleLaserState.sqf
addons/editor/initKeybinds.sqf
addons/editor/stringtable.xml

- title, pairs nicely with the force fire keybind
- Useful because we don't list laser weapons in the context menu action for switching vehicle weapons and this would be much faster than switching back and forth between laser and missiles (for example)

Add Toggle Laser keybind

---

addons/placement/XEH_postInit.sqf
addons/placement/functions/fnc_handleTreeChange.sqf

- title, because placement preview creates a local object of the selected type, selecting a module in the recent tree would bring up its dialog (instead we just ignore modules)

Fix placement preview activating modules in recent tree

---

addons/ai/functions/fnc_unGarrison.sqf

- Fix a typo that results in the garrisoned flag not be set false when ungarrisoned
- This causes issues with mods such a ZHC that check this flag.

Fix typo for garrisoned flag

---

addons/editor/functions/fnc_pingCurators.sqf
addons/editor/initKeybinds.sqf

- Use `profileName` to get the name to display for Zeus pings
- Not sure why but, in testing, `name` would sometimes display "Error: No vehicle" (this should avoid that)

Use profile name for Ping Zeus keybind

---

addons/attributes/initAttributes.sqf
addons/attributes/initSettings.sqf
addons/attributes/stringtable.xml
addons/common/XEH_postInit.sqf

- Add attributes for supply vehicles to adjust their supply cargo

Add Supply Cargo Attributes

---

addons/inventory/functions/fnc_refresh.sqf

- Title. See attached screenshots.
Filter doesn't have to be an exact match now and whitespace allows for looking ahead in the result.

Inventory - Use regex in searchbar

---

.hemtt/hooks/post_release/01_rename_zip.rhai
.hemtt/project.toml

- title, release zip archives were not named correctly

Fix HEMTT launch warning and post release hook

---

addons/common/functions/fnc_changeGroupSide.sqf

- Fixes using undefined ``_unit`` variable in #763 instead of ``_group``. 
Side change logic worked when tested in editor after this change.

fixed using undefined variable for sidechange instead of group

---

.hemtt/lints.toml
addons/ai/functions/fnc_canThrowGrenade.sqf
addons/ai/functions/fnc_garrison.sqf
addons/ai/functions/fnc_searchBuilding.sqf
addons/area_markers/functions/fnc_applyProperties.sqf
addons/area_markers/functions/fnc_createMarker.sqf
addons/common/functions/fnc_displayCuratorLoad.sqf
addons/common/functions/fnc_serializeObjects.sqf
addons/common/gui.hpp
addons/context_actions/functions/fnc_teleportZeus.sqf
addons/cover_map/functions/fnc_create.sqf
addons/editor/initKeybinds.inc.sqf
addons/modules/functions/fnc_moduleTeleportPlayers.sqf

- Fix L-C11ME (missing file extension)
- Apply L-S24 (repeated calls to global marker updates)
- Apply L-S18 (inefficient "not in vehicle" check)
- Ignore L-S17 (all caps variable)

General - Fix and apply HEMTT suggestions

---

addons/modules/functions/fnc_moduleAttachFlag.sqf

- https://github.com/zen-mod/ZEN/pull/749 was made for PortableFlagPole_01_F (which was added in the 2.14 update) but it was not actually supported.
- This change allows the change to be applied to all flags based on FlagCarrierCore other than Flag Pole. (FlagChecked_F is also included)

Fix Attach Flag module not supporting all flag pole types

---

addons/dialog/functions/fnc_create.sqf
addons/dialog/functions/fnc_gui_vector.sqf
addons/dialog/gui.hpp
docs/frameworks/dynamic_dialog.md

- Add subtype SIZE to VECTOR. This subtype doesn't allow negative numbers by default.
- Allow setting min and max values for each vector component. The user will still be able to enter values outside the limits. The values are clipped after confirmation. This behavior is the same in 3DEN.
- Add setting to only allow integer values

Dialog - Add sub-type `VECTOR:SIZE` & options to set min and max values
